CREATE WAREHOUSE IF NOT EXISTS CLAUSE_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE DATABASE IF NOT EXISTS CLAUSE_DB;
CREATE SCHEMA IF NOT EXISTS CLAUSE_DB.PUBLIC;
CREATE TABLE IF NOT EXISTS CLAUSE_DB.PUBLIC.STATUTES (
  id       STRING,
  chapter  STRING,
  section  STRING,
  title    STRING,
  text     STRING,
  embedding VECTOR(FLOAT, 768)
);
